accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$',views.signup_view,name="signup"),
    url(r'^login/$',views.login_view,name="login"),
    url(r'^logout/$',views.logout_view,name="logout"),
]

articles/urls.py
from django.conf.urls import url
from . import views

app_name = 'articles'

urlpatterns = [
    url(r'^$',views.article_list, name="list"),
    url(r'^(?P<slug>[\w-]+)/$',views.article_detail,name="detail"),
]

first_blog/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.home),
    url(r'^about/$',views.about),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^articles/',include('articles.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models

# Create your models here.


class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png',blank=True)
    #Add thumbnail later
    #Add author later

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + "..."

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm ,AuthenticationForm
from django.contrib.auth import login ,logout
# Create your views here.

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            #log the user in
            login(request,user)
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request,'accounts/signup.html',{'form':form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            #user log in
            user = form.get_user()
            login(request,user)
            return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request,'accounts/login.html',{'form':form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
    return redirect('articles:list')

articles/views.py
from django.shortcuts import render
from .models import Article
from django.http import HttpResponse
# Create your views here.

def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request,'articles/article_list.html',{'articles':articles})

def article_detail(request,slug):
    # return HttpResponse(slug)
    article = Article.objects.get(slug=slug)
    return render(request,'articles/article_detail.html',{'article':article})

first_blog/views.py
from django.http import HttpResponse
from django.shortcuts import render


def home(request):
    # return HttpResponse ("Welcome to home")
    return render(request,"home.html")

def about(request):
    # return HttpResponse("this is about ")
    return render(request,"about.html")

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Login Here</h1>
    <form class="site-form" action="{% url 'articles:list' %}" method="post">
    {% csrf_token %}
        {{ form }}
    <input type="submit" value="Login">
    </form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Signup here</h1>
    <form class="site-form" action="/accounts/signup/" method="post">
    {% csrf_token %}
     {{ form }}
    <input type="submit" value="Signup">
    </form>
{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
     <div class="article-detail">
        <div class="article">
            <img src="{{ article.thumb.url }}"/>
            <h2>{{ article.title }}</h2>
            <p>{{ article.body }}</p>
            <p>{{ article.date }}</p>
        </div>
     </div>
{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Articles list is Here</h1>

    <div class="articles">
        {% for article in articles %}
            <div class="article">
            <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a></h2>
            <p>{{ article.snippet }}</p>
            <p>{{ article.date}}</p>
            </div>
        {% endfor %}
    </div>

{% endblock %}
  

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>about</title>
</head>
<body>
        <h1>About US</h1>
        <p>We like django</p>

</body>
</html>

templates/base_layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>Articles detail</title>
</head>
<body>
    <div class="wrapper">
        <h1><a href="{% url 'articles:list' %}"><img src="{% static 'logo.png' %}"></a></h1>
        <nav>
            <ul>
                <li>
                    <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                    {% csrf_token %}
                     <button type="submit">Logout</button>
                    </form>
                </li>
            </ul>


        </nav>
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
    <h1>Welcome on home</h1>
    <p>Django is awesome</p>
</body>
</html>